version: '3'
services:
  db:
    image: postgres:14.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "gotask"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: